spring.application.name=galeri
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.jpa.properties.hibernate.default_schema=galeri
spring.datasource.password=1

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET:9ab3074aa5abcda49f0d54e8914f70e2eade98a099ffc63dacbbac2645f77d}